### ISSUE TITLE
build fails with make

### ISSUE THREAD

**Issue by hardikdangar** [coffnix/mysar-ng#10]
Hello,

i tired to build as per your instruction in docs but it fails with this,

root@host1:/srv/www/htdocs/mysar/bin/mysar-binary-importer# make clean && make

Making all in src
make[1]: Entering directory '/srv/www/htdocs/mysar/bin/mysar-binary-importer/src'
make  all-am
make[2]: Entering directory '/srv/www/htdocs/mysar/bin/mysar-binary-importer/src'
if gcc -DHAVE_CONFIG_H -I. -I. -I.    -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -MT mysar-mysar.o -MD -MP -MF ".deps/mysar-mysar.Tpo" -c -o mysar-mysar.o `test -f 'mysar.c' || echo './'`mysar.c; \
then mv -f ".deps/mysar-mysar.Tpo" ".deps/mysar-mysar.Po"; else rm -f ".deps/mysar-mysar.Tpo"; exit 1; fi
In file included from mysar.c:35:0:
mysar.h:152:13: warning: inline function ‘MySAR_import_summaries’ declared but never defined
 inline void MySAR_import_summaries();
             ^
mysar.h:151:13: warning: inline function ‘MySAR_import_users’ declared but never defined
 inline void MySAR_import_users();
             ^
mysar.h:150:13: warning: inline function ‘MySAR_import_sites’ declared but never defined
 inline void MySAR_import_sites();
             ^
mysar.h:149:13: warning: inline function ‘MySAR_import_hostnames’ declared but never defined
 inline void MySAR_import_hostnames();
             ^
mysar.h:148:13: warning: inline function ‘MySAR_import_traffic’ declared but never defined
 inline void MySAR_import_traffic();
             ^
if gcc -DHAVE_CONFIG_H -I. -I. -I.    -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -MT mysar-database.o -MD -MP -MF ".deps/mysar-database.Tpo" -c -o mysar-database.o `test -f 'database.c' || echo './'`database.c; \
then mv -f ".deps/mysar-database.Tpo" ".deps/mysar-database.Po"; else rm -f ".deps/mysar-database.Tpo"; exit 1; fi
In file included from database.c:30:0:
mysar.h:152:13: warning: inline function ‘MySAR_import_summaries’ declared but never defined
 inline void MySAR_import_summaries();
             ^
mysar.h:151:13: warning: inline function ‘MySAR_import_users’ declared but never defined
 inline void MySAR_import_users();
             ^
mysar.h:150:13: warning: inline function ‘MySAR_import_sites’ declared but never defined
 inline void MySAR_import_sites();
             ^
mysar.h:149:13: warning: inline function ‘MySAR_import_hostnames’ declared but never defined
 inline void MySAR_import_hostnames();
             ^
mysar.h:148:13: warning: inline function ‘MySAR_import_traffic’ declared but never defined
 inline void MySAR_import_traffic();
             ^
if gcc -DHAVE_CONFIG_H -I. -I. -I.    -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -MT mysar-sql.o -MD -MP -MF ".deps/mysar-sql.Tpo" -c -o mysar-sql.o `test -f 'sql.c' || echo './'`sql.c; \
then mv -f ".deps/mysar-sql.Tpo" ".deps/mysar-sql.Po"; else rm -f ".deps/mysar-sql.Tpo"; exit 1; fi
sql.c: In function ‘MySAR_fetch_configvalue’:
sql.c:143:2: warning: implicit declaration of function ‘asprintf’ [-Wimplicit-function-declaration]
  asprintf(&return_result, "%s", row[0]);
  ^
if gcc -DHAVE_CONFIG_H -I. -I. -I.    -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -MT mysar-utils.o -MD -MP -MF ".deps/mysar-utils.Tpo" -c -o mysar-utils.o `test -f 'utils.c' || echo './'`utils.c; \
then mv -f ".deps/mysar-utils.Tpo" ".deps/mysar-utils.Po"; else rm -f ".deps/mysar-utils.Tpo"; exit 1; fi
In file included from utils.c:24:0:
mysar.h:152:13: warning: inline function ‘MySAR_import_summaries’ declared but never defined
 inline void MySAR_import_summaries();
             ^
mysar.h:151:13: warning: inline function ‘MySAR_import_users’ declared but never defined
 inline void MySAR_import_users();
             ^
mysar.h:150:13: warning: inline function ‘MySAR_import_sites’ declared but never defined
 inline void MySAR_import_sites();
             ^
mysar.h:149:13: warning: inline function ‘MySAR_import_hostnames’ declared but never defined
 inline void MySAR_import_hostnames();
             ^
mysar.h:148:13: warning: inline function ‘MySAR_import_traffic’ declared but never defined
 inline void MySAR_import_traffic();
             ^
if gcc -DHAVE_CONFIG_H -I. -I. -I.    -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -MT mysar-unzip.o -MD -MP -MF ".deps/mysar-unzip.Tpo" -c -o mysar-unzip.o `test -f 'unzip.c' || echo './'`unzip.c; \
then mv -f ".deps/mysar-unzip.Tpo" ".deps/mysar-unzip.Po"; else rm -f ".deps/mysar-unzip.Tpo"; exit 1; fi
In file included from unzip.c:24:0:
mysar.h:152:13: warning: inline function ‘MySAR_import_summaries’ declared but never defined
 inline void MySAR_import_summaries();
             ^
mysar.h:151:13: warning: inline function ‘MySAR_import_users’ declared but never defined
 inline void MySAR_import_users();
             ^
mysar.h:150:13: warning: inline function ‘MySAR_import_sites’ declared but never defined
 inline void MySAR_import_sites();
             ^
mysar.h:149:13: warning: inline function ‘MySAR_import_hostnames’ declared but never defined
 inline void MySAR_import_hostnames();
             ^
mysar.h:148:13: warning: inline function ‘MySAR_import_traffic’ declared but never defined
 inline void MySAR_import_traffic();
             ^
if gcc -DHAVE_CONFIG_H -I. -I. -I.    -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -MT mysar-debug.o -MD -MP -MF ".deps/mysar-debug.Tpo" -c -o mysar-debug.o `test -f 'debug.c' || echo './'`debug.c; \
then mv -f ".deps/mysar-debug.Tpo" ".deps/mysar-debug.Po"; else rm -f ".deps/mysar-debug.Tpo"; exit 1; fi
debug.c: In function ‘MySAR_macro_print_msg’:
debug.c:61:2: warning: implicit declaration of function ‘vasprintf’ [-Wimplicit-function-declaration]
  vasprintf (&result,fmt,ap);
  ^
In file included from debug.c:31:0:
debug.c: At top level:
mysar.h:152:13: warning: inline function ‘MySAR_import_summaries’ declared but never defined
 inline void MySAR_import_summaries();
             ^
mysar.h:151:13: warning: inline function ‘MySAR_import_users’ declared but never defined
 inline void MySAR_import_users();
             ^
mysar.h:150:13: warning: inline function ‘MySAR_import_sites’ declared but never defined
 inline void MySAR_import_sites();
             ^
mysar.h:149:13: warning: inline function ‘MySAR_import_hostnames’ declared but never defined
 inline void MySAR_import_hostnames();
             ^
mysar.h:148:13: warning: inline function ‘MySAR_import_traffic’ declared but never defined
 inline void MySAR_import_traffic();
             ^
if gcc -DHAVE_CONFIG_H -I. -I. -I.    -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -MT mysar-config.o -MD -MP -MF ".deps/mysar-config.Tpo" -c -o mysar-config.o `test -f 'config.c' || echo './'`config.c; \
then mv -f ".deps/mysar-config.Tpo" ".deps/mysar-config.Po"; else rm -f ".deps/mysar-config.Tpo"; exit 1; fi
In file included from config.c:25:0:
mysar.h:152:13: warning: inline function ‘MySAR_import_summaries’ declared but never defined
 inline void MySAR_import_summaries();
             ^
mysar.h:151:13: warning: inline function ‘MySAR_import_users’ declared but never defined
 inline void MySAR_import_users();
             ^
mysar.h:150:13: warning: inline function ‘MySAR_import_sites’ declared but never defined
 inline void MySAR_import_sites();
             ^
mysar.h:149:13: warning: inline function ‘MySAR_import_hostnames’ declared but never defined
 inline void MySAR_import_hostnames();
             ^
mysar.h:148:13: warning: inline function ‘MySAR_import_traffic’ declared but never defined
 inline void MySAR_import_traffic();
             ^
config.c: In function ‘MySAR_parse_config_file’:
config.c:189:4: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
    fgets(line,512,f);
    ^
if gcc -DHAVE_CONFIG_H -I. -I. -I.    -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -MT mysar-lock.o -MD -MP -MF ".deps/mysar-lock.Tpo" -c -o mysar-lock.o `test -f 'lock.c' || echo './'`lock.c; \
then mv -f ".deps/mysar-lock.Tpo" ".deps/mysar-lock.Po"; else rm -f ".deps/mysar-lock.Tpo"; exit 1; fi
In file included from lock.c:32:0:
mysar.h:152:13: warning: inline function ‘MySAR_import_summaries’ declared but never defined
 inline void MySAR_import_summaries();
             ^
mysar.h:151:13: warning: inline function ‘MySAR_import_users’ declared but never defined
 inline void MySAR_import_users();
             ^
mysar.h:150:13: warning: inline function ‘MySAR_import_sites’ declared but never defined
 inline void MySAR_import_sites();
             ^
mysar.h:149:13: warning: inline function ‘MySAR_import_hostnames’ declared but never defined
 inline void MySAR_import_hostnames();
             ^
mysar.h:148:13: warning: inline function ‘MySAR_import_traffic’ declared but never defined
 inline void MySAR_import_traffic();
             ^
gcc  -g -O2   -o mysar  mysar-mysar.o mysar-database.o mysar-sql.o mysar-utils.o mysar-unzip.o mysar-debug.o mysar-config.o mysar-lock.o  -lz -lmysqlclient -lmysqlclient 
mysar-mysar.o: In function `main':
/srv/www/htdocs/mysar/bin/mysar-binary-importer/src/mysar.c:363: undefined reference to `MySAR_import_sites'
/srv/www/htdocs/mysar/bin/mysar-binary-importer/src/mysar.c:364: undefined reference to `MySAR_import_users'
/srv/www/htdocs/mysar/bin/mysar-binary-importer/src/mysar.c:365: undefined reference to `MySAR_import_hostnames'
/srv/www/htdocs/mysar/bin/mysar-binary-importer/src/mysar.c:367: undefined reference to `MySAR_import_traffic'
/srv/www/htdocs/mysar/bin/mysar-binary-importer/src/mysar.c:369: undefined reference to `MySAR_import_summaries'
collect2: error: ld returned 1 exit status
Makefile:235: recipe for target 'mysar' failed
make[2]: *** [mysar] Error 1
make[2]: Leaving directory '/srv/www/htdocs/mysar/bin/mysar-binary-importer/src'
Makefile:161: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/srv/www/htdocs/mysar/bin/mysar-binary-importer/src'
Makefile:228: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by coffnix** [comment]
Compile fine on all distros. Go look for ubuntu support and stop asking stupid questions here.

**Comment by coffnix** [comment]
Take a look:
http://pastebin.com/ztjPfiFt

**Comment by bzero** [comment]
@hardikdangar remove inline keyword from file src/mysar.h

**Comment by bzero** [comment]
git diff mysar.h
diff --git a/mysar/bin/mysar-binary-importer/src/mysar.h b/mysar/bin/mysar-binary-importer/src/mysar.h
index 5a1788d..80d08f3 100644
--- a/mysar/bin/mysar-binary-importer/src/mysar.h
+++ b/mysar/bin/mysar-binary-importer/src/mysar.h
@@ -145,11 +145,11 @@ char *MySAR_fetch_configvalue(char *);
 char *MySAR_select_field();
 void MySAR_prep_mysql();
 void MySAR_free_mysql_statements();
-inline void MySAR_import_traffic();
-inline void MySAR_import_hostnames();
-inline void MySAR_import_sites();
-inline void MySAR_import_users();
-inline void MySAR_import_summaries();
+void MySAR_import_traffic();
+void MySAR_import_hostnames();
+void MySAR_import_sites();
+void MySAR_import_users();
+void MySAR_import_summaries();
 long MySAR_fetch_config_long(char *name);
 int MySAR_update_config_long(long value, char *name);

**Comment by hardikdangar** [comment]
@bzero 

thanks your solution works.
how do you know that inline is needed to removed from source ?
My c++ is not as good as yours.

Thank you very much for your help.

@coffnix sorry dude i posted here. reason behind posting here is anybody who faces this issue knows how this can be resolved. because first place people will search is your repo if they are using your source.
