### ISSUE TITLE
Multiple Vulnerabilities

### ISSUE THREAD

**Issue by this-post** [coffnix/mysar-ng#12]
SQL Injection and Reflected Cross-Site Script vulnerability are found on ***almost*** parameters in /mysar/www/index.php

Example vulnerable code (SQL Injection):

$query='SELECT '.
			'authuser'.
			' FROM '.
			'users'.
			' WHERE '.
			'id=\''.$_REQUEST['usersID'].'\''; // <---- vulnerable
		$currentAuthuser=db_select_one_row($link, $query);
===============================

Example vulnerable code (XSS):

***/mysar/www/index.php***
if(empty($_REQUEST['a'])) {
	$pageVars['thisPage']='index'; // <---- vulnerable (user supplied input without filtering or any htmlencode())

***example template file***
{if $pageVars.previousWeekID != ""}
      <a href="{$smarty.server.PHP_SELF}?a={$pageVars.thisPage}&hostiplong={$pageVars.hostiplong}&date={$pageVars.previousWeek}&usersID={$pageVars.previousWeekID}">&lt;&lt;</a>
	{/if} <!-- {$pageVars.thisPage} receive the input from index.php and echo malicious input (html or Javascript)
================================

**Comment by coffnix** [comment]
you have any patch?

**Comment by mainuk18** [comment]
Need use https://github.com/arturolegovich/PasswordChain/blob/main/libs/ValidateRequests.class.php for smarty from PHPChain.
I'll fix it in time.

**Comment by coffnix** [comment]
smarty updated to 4.3. Please make more tests.
