### ISSUE TITLE
mysar-binary-importer undefined reference

### ISSUE THREAD

**Issue by acoul** [coffnix/mysar-ng#13]
compiling mysar-binary-importer on current gcc gives the following error:

`mysar-binary-importer/src/mysar.c:363: undefined reference to `MySAR_import_sites'`

adding `extern` infront of the `inline` definitions in mysar.h fixes the problems

  -inline void MySAR_import_traffic();
  -inline void MySAR_import_hostnames();
  -inline void MySAR_import_sites();
  -inline void MySAR_import_users();
  -inline void MySAR_import_summaries();
  +extern inline void MySAR_import_traffic();
  +extern inline void MySAR_import_hostnames();
  +extern inline void MySAR_import_sites();
  +extern inline void MySAR_import_users();
  +extern inline void MySAR_import_summaries();

**Comment by coffnix** [comment]
fixed on commit https://github.com/coffnix/mysar-ng/commit/ba55ead92cf593d5c9b06352b400a175a519fb62

thanks again!
