### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by gsvasan01** [coffnix/mysar-ng#15]
MySAR 2.1.4 Log importer, 64 bit Version
Copyright 2007 Cassiano Martin
Last Database cleanup performed on 2022-12-16
History keep days: 32
Current Date 2022-12-16
Loading plain text log file...
Segmentation fault

kernel: [81041.542228] mysar[3969]: segfault at 38 ip 00007fa1e6a0014b sp 00007ffc08a73be0 error 4 in libmariadb.so.3[7fa1e69ea000+24000]

**Comment by coffnix** [comment]
please run mysar --debug

**Comment by coffnix** [comment]
fixed in https://github.com/area31/mysar-ng/commit/d05c74c6433f3f87187b6952601f0e1c01c6aa92
