### ISSUE TITLE
ubuntu 16.04: cannot build binary importer

### ISSUE THREAD

**Issue by hardikdangar** [coffnix/mysar-ng#9]
in ubuntu 16.04 i have tried to build via following command,

`cd /srv/www/htdocs/mysar/bin/mysar-binary-importer/ ; make clean && make && make install
`
and it fails with following output

/bin/sh ./config.status --recheck
expr: non-integer argument

expr: non-integer argument is printed on loop until i close the command explicitly.

I have gcc installed as well as build tools for ubuntu installed.

gcc version is,
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
```

**Comment by coffnix** [comment]
Hi,

Try run ./configure first. ;)

Ex:
# ./configure && make && make install

**Comment by coffnix** [comment]
RTFM: https://github.com/coffnix/mysar-ng/blob/master/mysar/bin/mysar-binary-importer/INSTALL



The simplest way to compile this package is:

  1. `cd' to the directory containing the package's source code and type
     `./configure' to configure the package for your system.  If you're
     using `csh' on an old version of System V, you might need to type
     `sh ./configure' instead to prevent `csh' from trying to execute
     `configure' itself.

     Running `configure' takes awhile.  While running, it prints some
     messages telling which features it is checking for.

  2. Type `make' to compile the package.

**Comment by hardikdangar** [comment]
Hey,

I tried with ./configure,

but it fails with following output,
```

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for mysql_init in -lmysqlclient... no
checking for mysql_init in -lmysqlclient... no
checking for mysql_init in -lmysqlclient... no
checking for mysql_init in -lmysqlclient... no
checking for mysql_init in -lmysqlclient... no
checking for mysql_init in -lmysqlclient... no
checking for mysql_init in -lmysqlclient... no
configure: error: MySQL libraries not found.  Use --with-mysql-lib=<path>
```

after looking at error message it seems its trying to search mysql lib and fails so i tried it with,

./configure --with-mysql-lib=/usr/lib/mysql

but it fails with the same message.

**Comment by coffnix** [comment]
You need libmysqlclient-dev. Please, READ THE FUCKING MANUAL!!!!!! 

Stop asking stupid questions. Learn how to use your distribution (ubuntu in this case).

**Comment by bzero** [comment]
@hardikdangar: sudo apt install libmysqlclient-dev

**Comment by hardikdangar** [comment]
Sorry about that but that readme file does not say libmysqlclient-dev. i already installed both mysql-server and mysql-client.

also ./configure wasn't specified in the original github page were instruction to build is specified. it was honest mistkae i sould've figure it out.

So sorry for the troubles.

**Comment by coffnix** [comment]
You should look for this type of technical support in the official ubuntu channel.
